context:
  name: pixi-pack
  version: "0.6.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/quantco/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: b43c2e227e265e5ff7436e8ec7a6be1df85931cc85a0b4a717be6c26c2760305
build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: unix
      then: [openssl]

tests:
  - script: pixi-pack --help

about:
  homepage: https://github.com/quantco/pixi-pack
  repository: https://github.com/quantco/pixi-pack
  summary: 📦 A tool to pack and unpack conda environments created with pixi
  documentation: https://pixi.sh/latest/deployment/pixi_pack
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - delsner
    - pavelzw
