context:
  name: pixi-pack
  version: "0.3.3"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/quantco/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 378edb90cfad421f56a354728d186b46a2246aebe1b07917319d8df5e5045f64
build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: unix
      then: [openssl]

tests:
  - script: pixi-pack --help

about:
  homepage: https://github.com/quantco/pixi-pack
  repository: https://github.com/quantco/pixi-pack
  summary: 📦 A tool to pack and unpack conda environments created with pixi
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - delsner
    - pavelzw
