context:
  name: pixi-pack
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/quantco/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a157edac4f8fa8c60f9512ad3f7215b41c6cb747cdc9043ca420eb2a7807bf22
build:
  number: 0

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: unix
      then: [openssl]

tests:
  - script: pixi-pack --help

about:
  homepage: https://github.com/quantco/pixi-pack
  repository: https://github.com/quantco/pixi-pack
  summary: 📦 A tool to pack and unpack conda environments created with pixi
  documentation: https://pixi.sh/latest/deployment/pixi_pack
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - delsner
    - pavelzw
