context:
  name: pixi-pack
  version: "0.7.3"

recipe:
  name: pixi-pack
  version: ${{ version }}

source:
  url: https://github.com/quantco/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 233e979028fc9c985fbb9b7173aa62f2aafba70b603310c4df9a35c966b00960

build:
  number: 0

outputs:
  - package:
      name: pixi-pack
      version: ${{ version }}
    build:
      script:
        env:
          CARGO_PROFILE_RELEASE_STRIP: symbols
          CARGO_PROFILE_RELEASE_LTO: fat
        content:
          - if: unix
            then: export OPENSSL_DIR=${{ PREFIX }}
          - cargo auditable install --locked --no-track --bin pixi-pack --root ${{ PREFIX }} --path .
          - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
    requirements:
      build:
        - ${{ compiler('rust') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - cargo-auditable
        - cargo-bundle-licenses
        - pkg-config
      host:
        - if: unix
          then: [openssl]
    tests:
      - script: pixi-pack --help
      - package_contents:
          bin: pixi-pack
          strict: true
  - package:
      name: pixi-unpack
      version: ${{ version }}
    build:
      script:
        env:
          CARGO_PROFILE_RELEASE_STRIP: symbols
          CARGO_PROFILE_RELEASE_LTO: fat
        content:
          - if: unix
            then: export OPENSSL_DIR=${{ PREFIX }}
          - cargo auditable install --locked --no-track --bin pixi-unpack --root ${{ PREFIX }} --path .
          - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
    requirements:
      build:
        - ${{ compiler('rust') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - cargo-auditable
        - cargo-bundle-licenses
        - pkg-config
      host:
        - if: unix
          then: [openssl]
    tests:
      - script: pixi-unpack --help
      - package_contents:
          bin: pixi-unpack
          strict: true

about:
  homepage: https://github.com/quantco/pixi-pack
  repository: https://github.com/quantco/pixi-pack
  summary: 📦 A toolset to pack and unpack conda environments created with pixi
  documentation: https://pixi.sh/latest/deployment/pixi_pack
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - delsner
    - pavelzw
