context:
  name: pixi-pack
  version: "0.6.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/quantco/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 43d795f8beba0553d11a65ff6e8606ee1d877313f07dbd0722d630cdcccaf0bb

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - pkg-config
  host:
    - if: unix
      then: [openssl]

tests:
  - script: pixi-pack --help

about:
  homepage: https://github.com/quantco/pixi-pack
  repository: https://github.com/quantco/pixi-pack
  summary: 📦 A tool to pack and unpack conda environments created with pixi
  documentation: https://pixi.sh/latest/deployment/pixi_pack
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - delsner
    - pavelzw
