context:
  name: pixi-pack
  version: "0.7.1"

source:
  url: https://github.com/quantco/${{ name }}/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 02c9f66d35061ddfbd690a632aafe4415d451762b1e755010a8b33b81285f686

outputs:
  - package:
      name: pixi-pack
      version: ${{ version }}
    build:
      number: 0
      script:
        env:
          CARGO_PROFILE_RELEASE_STRIP: symbols
          CARGO_PROFILE_RELEASE_LTO: fat
        content:
          - if: unix
            then: export OPENSSL_DIR=${{ PREFIX }}
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path . --bin pixi-pack
          - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
    requirements:
      build:
        - ${{ compiler('rust') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - cargo-auditable
        - cargo-bundle-licenses
        - pkg-config
      host:
        - if: unix
          then: [openssl]
    tests:
      - script: pixi-pack --help
  - package:
      name: pixi-unpack
      version: ${{ version }}
    build:
      number: 0
      script:
        env:
          CARGO_PROFILE_RELEASE_STRIP: symbols
          CARGO_PROFILE_RELEASE_LTO: fat
        content:
          - if: unix
            then: export OPENSSL_DIR=${{ PREFIX }}
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path . --bin pixi-pack
          - cargo-bundle-licenses --format yaml --output ./THIRDPARTY.yml
    requirements:
      build:
        - ${{ compiler('rust') }}
        - ${{ compiler('c') }}
        - ${{ stdlib('c') }}
        - cargo-auditable
        - cargo-bundle-licenses
        - pkg-config
      host:
        - if: unix
          then: [openssl]
    tests:
      - script: pixi-unpack --help

about:
  homepage: https://github.com/quantco/pixi-pack
  repository: https://github.com/quantco/pixi-pack
  summary: 📦 A toolset to pack and unpack conda environments created with pixi
  documentation: https://pixi.sh/latest/deployment/pixi_pack
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - THIRDPARTY.yml

extra:
  recipe-maintainers:
    - delsner
    - pavelzw
