build_platform:
  linux_aarch64: linux_64
  linux_ppc64le: linux_64
provider:
  osx_arm64: github_actions
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
conda_build_tool: rattler-build
conda_install_tool: pixi
github_actions:
  self_hosted: true
  timeout_minutes: 360
  triggers:
    - push
    - pull_request
